export const cudiSongs = [
  {
    title: 'Pursuit of Happiness',
    artist: 'Kid Cudi',
  },
  {
    title: "Day 'n' Nite",
    artist: 'Kid Cudi',
  },
  {
    title: 'Up Up & Away',
    artist: 'Kid Cudi',
  },
  {
    title: 'I Do My Thing',
    artist: 'Kid Cudi',
  },
  {
    title: 'Cleveland Is the Reason',
    artist: 'Kid Cudi',
  },
  {
    title: 'The Prayer',
    artist: 'Kid Cudi',
  },
  {
    title: 'The Rage',
    artist: 'Kid Cudi',
  },
  {
    title: 'Erase Me',
    artist: 'Kid Cudi',
  },
  {
    title: 'Soundtrack 2 My Life',
    artist: 'Kid Cudi',
  },
  {
    title: 'Make Her Say',
    artist: 'Kid Cudi',
  },
]

export const cudiSpotifySongs = [
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
          },
          href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
          id: '0fA0VVWsXO9YnASrzqfmYu',
          name: 'Kid Cudi',
          type: 'artist',
          uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
        },
      ],
      available_markets: ['CA', 'MX', 'US'],
      external_urls: {
        spotify: 'https://open.spotify.com/album/47y3PbX8oIDCkYAFylCJz0',
      },
      href: 'https://api.spotify.com/v1/albums/47y3PbX8oIDCkYAFylCJz0',
      id: '47y3PbX8oIDCkYAFylCJz0',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273aab2c3c3f1f3207137d915c9',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02aab2c3c3f1f3207137d915c9',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851aab2c3c3f1f3207137d915c9',
          width: 64,
        },
      ],
      name: 'Man On The Moon: The End Of Day',
      release_date: '2009-09-15',
      release_date_precision: 'day',
      total_tracks: 15,
      type: 'album',
      uri: 'spotify:album:47y3PbX8oIDCkYAFylCJz0',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
        },
        href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
        id: '0fA0VVWsXO9YnASrzqfmYu',
        name: 'Kid Cudi',
        type: 'artist',
        uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0SwO7SWeDHJijQ3XNS7xEE',
        },
        href: 'https://api.spotify.com/v1/artists/0SwO7SWeDHJijQ3XNS7xEE',
        id: '0SwO7SWeDHJijQ3XNS7xEE',
        name: 'MGMT',
        type: 'artist',
        uri: 'spotify:artist:0SwO7SWeDHJijQ3XNS7xEE',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/57dN52uHvrHOxijzpIgu3E',
        },
        href: 'https://api.spotify.com/v1/artists/57dN52uHvrHOxijzpIgu3E',
        id: '57dN52uHvrHOxijzpIgu3E',
        name: 'Ratatat',
        type: 'artist',
        uri: 'spotify:artist:57dN52uHvrHOxijzpIgu3E',
      },
    ],
    available_markets: ['CA', 'MX', 'US'],
    disc_number: 1,
    duration_ms: 295293,
    explicit: true,
    external_ids: {
      isrc: 'USUM70981907',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/5iSEsR6NKjlC9SrIJkyL3k',
    },
    href: 'https://api.spotify.com/v1/tracks/5iSEsR6NKjlC9SrIJkyL3k',
    id: '5iSEsR6NKjlC9SrIJkyL3k',
    is_local: false,
    name: 'Pursuit Of Happiness (Nightmare)',
    popularity: 74,
    preview_url:
      'https://p.scdn.co/mp3-preview/39b6e1e7e3de1bbb146f0aa7d77a8224e970da2d?cid=af012268d5474f01b5237163a54e9b06',
    track_number: 13,
    type: 'track',
    uri: 'spotify:track:5iSEsR6NKjlC9SrIJkyL3k',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
          },
          href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
          id: '0fA0VVWsXO9YnASrzqfmYu',
          name: 'Kid Cudi',
          type: 'artist',
          uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
        },
      ],
      available_markets: ['CA', 'MX', 'US'],
      external_urls: {
        spotify: 'https://open.spotify.com/album/2S8AWAM0nxyFy66YnUfIs3',
      },
      href: 'https://api.spotify.com/v1/albums/2S8AWAM0nxyFy66YnUfIs3',
      id: '2S8AWAM0nxyFy66YnUfIs3',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273a487deeecb334b6619489d74',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02a487deeecb334b6619489d74',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851a487deeecb334b6619489d74',
          width: 64,
        },
      ],
      name: 'Man On The Moon: The End Of Day (Deluxe)',
      release_date: '2009-01-01',
      release_date_precision: 'day',
      total_tracks: 18,
      type: 'album',
      uri: 'spotify:album:2S8AWAM0nxyFy66YnUfIs3',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
        },
        href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
        id: '0fA0VVWsXO9YnASrzqfmYu',
        name: 'Kid Cudi',
        type: 'artist',
        uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
      },
    ],
    available_markets: ['CA', 'MX', 'US'],
    disc_number: 1,
    duration_ms: 221240,
    explicit: false,
    external_ids: {
      isrc: 'USUM70957500',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/5wfllwdjglyQislkskYLBv',
    },
    href: 'https://api.spotify.com/v1/tracks/5wfllwdjglyQislkskYLBv',
    id: '5wfllwdjglyQislkskYLBv',
    is_local: false,
    name: "Day 'N' Nite (nightmare)",
    popularity: 72,
    preview_url:
      'https://p.scdn.co/mp3-preview/1861b564aae0c5239f3c6a022238677e9b6c20be?cid=af012268d5474f01b5237163a54e9b06',
    track_number: 7,
    type: 'track',
    uri: 'spotify:track:5wfllwdjglyQislkskYLBv',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
          },
          href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
          id: '0fA0VVWsXO9YnASrzqfmYu',
          name: 'Kid Cudi',
          type: 'artist',
          uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
        },
      ],
      available_markets: ['CA', 'MX', 'US'],
      external_urls: {
        spotify: 'https://open.spotify.com/album/2S8AWAM0nxyFy66YnUfIs3',
      },
      href: 'https://api.spotify.com/v1/albums/2S8AWAM0nxyFy66YnUfIs3',
      id: '2S8AWAM0nxyFy66YnUfIs3',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273a487deeecb334b6619489d74',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02a487deeecb334b6619489d74',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851a487deeecb334b6619489d74',
          width: 64,
        },
      ],
      name: 'Man On The Moon: The End Of Day (Deluxe)',
      release_date: '2009-01-01',
      release_date_precision: 'day',
      total_tracks: 18,
      type: 'album',
      uri: 'spotify:album:2S8AWAM0nxyFy66YnUfIs3',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
        },
        href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
        id: '0fA0VVWsXO9YnASrzqfmYu',
        name: 'Kid Cudi',
        type: 'artist',
        uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
      },
    ],
    available_markets: ['CA', 'MX', 'US'],
    disc_number: 1,
    duration_ms: 227346,
    explicit: true,
    external_ids: {
      isrc: 'USUM70981911',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/1RUTIdTnFs8lHSc0Zr4UJB',
    },
    href: 'https://api.spotify.com/v1/tracks/1RUTIdTnFs8lHSc0Zr4UJB',
    id: '1RUTIdTnFs8lHSc0Zr4UJB',
    is_local: false,
    name: 'Up Up & Away',
    popularity: 63,
    preview_url:
      'https://p.scdn.co/mp3-preview/729778989b7d2d5e3efd41e1a2e47c278272a770?cid=af012268d5474f01b5237163a54e9b06',
    track_number: 15,
    type: 'track',
    uri: 'spotify:track:1RUTIdTnFs8lHSc0Zr4UJB',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
          },
          href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
          id: '0fA0VVWsXO9YnASrzqfmYu',
          name: 'Kid Cudi',
          type: 'artist',
          uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/2blXZboio9DF8VC39LmUag',
      },
      href: 'https://api.spotify.com/v1/albums/2blXZboio9DF8VC39LmUag',
      id: '2blXZboio9DF8VC39LmUag',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273cd4666c02c9749c71dabb8ea',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02cd4666c02c9749c71dabb8ea',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851cd4666c02c9749c71dabb8ea',
          width: 64,
        },
      ],
      name: 'A Kid Named Cudi',
      release_date: '2022-07-15',
      release_date_precision: 'day',
      total_tracks: 16,
      type: 'album',
      uri: 'spotify:album:2blXZboio9DF8VC39LmUag',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
        },
        href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
        id: '0fA0VVWsXO9YnASrzqfmYu',
        name: 'Kid Cudi',
        type: 'artist',
        uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 225586,
    explicit: true,
    external_ids: {
      isrc: 'USUM72213194',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/64t5bg43EQzlCZbzACMhEl',
    },
    href: 'https://api.spotify.com/v1/tracks/64t5bg43EQzlCZbzACMhEl',
    id: '64t5bg43EQzlCZbzACMhEl',
    is_local: false,
    name: 'Cleveland Is The Reason',
    popularity: 46,
    preview_url:
      'https://p.scdn.co/mp3-preview/516c684126c3063d9c71ce7a0eda82032e1796cb?cid=af012268d5474f01b5237163a54e9b06',
    track_number: 15,
    type: 'track',
    uri: 'spotify:track:64t5bg43EQzlCZbzACMhEl',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
          },
          href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
          id: '0fA0VVWsXO9YnASrzqfmYu',
          name: 'Kid Cudi',
          type: 'artist',
          uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PS',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/2blXZboio9DF8VC39LmUag',
      },
      href: 'https://api.spotify.com/v1/albums/2blXZboio9DF8VC39LmUag',
      id: '2blXZboio9DF8VC39LmUag',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273cd4666c02c9749c71dabb8ea',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02cd4666c02c9749c71dabb8ea',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851cd4666c02c9749c71dabb8ea',
          width: 64,
        },
      ],
      name: 'A Kid Named Cudi',
      release_date: '2022-07-15',
      release_date_precision: 'day',
      total_tracks: 16,
      type: 'album',
      uri: 'spotify:album:2blXZboio9DF8VC39LmUag',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
        },
        href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
        id: '0fA0VVWsXO9YnASrzqfmYu',
        name: 'Kid Cudi',
        type: 'artist',
        uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 219093,
    explicit: true,
    external_ids: {
      isrc: 'USUM72213186',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/1SkzK37qLSi7Sp6PwYTC0A',
    },
    href: 'https://api.spotify.com/v1/tracks/1SkzK37qLSi7Sp6PwYTC0A',
    id: '1SkzK37qLSi7Sp6PwYTC0A',
    is_local: false,
    name: 'The Prayer',
    popularity: 64,
    preview_url:
      'https://p.scdn.co/mp3-preview/36e0d4d302dd016e5c88fb4a4651c8087cb2c818?cid=af012268d5474f01b5237163a54e9b06',
    track_number: 6,
    type: 'track',
    uri: 'spotify:track:1SkzK37qLSi7Sp6PwYTC0A',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
          },
          href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
          id: '0fA0VVWsXO9YnASrzqfmYu',
          name: 'Kid Cudi',
          type: 'artist',
          uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/08eM9GRdr5BCCHNqS3Wwud',
      },
      href: 'https://api.spotify.com/v1/albums/08eM9GRdr5BCCHNqS3Wwud',
      id: '08eM9GRdr5BCCHNqS3Wwud',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b27359e842b6a3566a141f27f815',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e0259e842b6a3566a141f27f815',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d0000485159e842b6a3566a141f27f815',
          width: 64,
        },
      ],
      name: 'Man On The Moon II: The Legend Of Mr. Rager',
      release_date: '2010-11-09',
      release_date_precision: 'day',
      total_tracks: 17,
      type: 'album',
      uri: 'spotify:album:08eM9GRdr5BCCHNqS3Wwud',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
        },
        href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
        id: '0fA0VVWsXO9YnASrzqfmYu',
        name: 'Kid Cudi',
        type: 'artist',
        uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/5nLYd9ST4Cnwy6NHaCxbj8',
        },
        href: 'https://api.spotify.com/v1/artists/5nLYd9ST4Cnwy6NHaCxbj8',
        id: '5nLYd9ST4Cnwy6NHaCxbj8',
        name: 'CeeLo Green',
        type: 'artist',
        uri: 'spotify:artist:5nLYd9ST4Cnwy6NHaCxbj8',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 235293,
    explicit: true,
    external_ids: {
      isrc: 'USUM71025496',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/5QemHQxj7PRkrw8lJl2W7C',
    },
    href: 'https://api.spotify.com/v1/tracks/5QemHQxj7PRkrw8lJl2W7C',
    id: '5QemHQxj7PRkrw8lJl2W7C',
    is_local: false,
    name: 'Scott Mescudi Vs. The World',
    popularity: 56,
    preview_url:
      'https://p.scdn.co/mp3-preview/75fb2b7cdf2d75fda7338303bc6fcd70751516d7?cid=af012268d5474f01b5237163a54e9b06',
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:5QemHQxj7PRkrw8lJl2W7C',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
          },
          href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
          id: '0fA0VVWsXO9YnASrzqfmYu',
          name: 'Kid Cudi',
          type: 'artist',
          uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AG',
        'AL',
        'AM',
        'AO',
        'AR',
        'AT',
        'AU',
        'AZ',
        'BA',
        'BB',
        'BD',
        'BE',
        'BF',
        'BG',
        'BH',
        'BI',
        'BJ',
        'BN',
        'BO',
        'BR',
        'BS',
        'BT',
        'BW',
        'BY',
        'BZ',
        'CA',
        'CD',
        'CG',
        'CH',
        'CI',
        'CL',
        'CM',
        'CO',
        'CR',
        'CV',
        'CW',
        'CY',
        'CZ',
        'DE',
        'DJ',
        'DK',
        'DM',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'ET',
        'FI',
        'FJ',
        'FM',
        'FR',
        'GA',
        'GB',
        'GD',
        'GE',
        'GH',
        'GM',
        'GN',
        'GQ',
        'GR',
        'GT',
        'GW',
        'GY',
        'HK',
        'HN',
        'HR',
        'HT',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IQ',
        'IS',
        'IT',
        'JM',
        'JO',
        'JP',
        'KE',
        'KG',
        'KH',
        'KI',
        'KM',
        'KN',
        'KR',
        'KW',
        'KZ',
        'LA',
        'LB',
        'LC',
        'LI',
        'LK',
        'LR',
        'LS',
        'LT',
        'LU',
        'LV',
        'LY',
        'MA',
        'MC',
        'MD',
        'ME',
        'MG',
        'MH',
        'MK',
        'ML',
        'MN',
        'MO',
        'MR',
        'MT',
        'MU',
        'MV',
        'MW',
        'MX',
        'MY',
        'MZ',
        'NA',
        'NE',
        'NG',
        'NI',
        'NL',
        'NO',
        'NP',
        'NR',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PG',
        'PH',
        'PK',
        'PL',
        'PT',
        'PW',
        'PY',
        'QA',
        'RO',
        'RS',
        'RW',
        'SA',
        'SB',
        'SC',
        'SE',
        'SG',
        'SI',
        'SK',
        'SL',
        'SM',
        'SN',
        'SR',
        'ST',
        'SV',
        'SZ',
        'TD',
        'TG',
        'TH',
        'TJ',
        'TL',
        'TN',
        'TO',
        'TR',
        'TT',
        'TV',
        'TW',
        'TZ',
        'UA',
        'UG',
        'US',
        'UY',
        'UZ',
        'VC',
        'VE',
        'VN',
        'VU',
        'WS',
        'XK',
        'ZA',
        'ZM',
        'ZW',
      ],
      external_urls: {
        spotify: 'https://open.spotify.com/album/08eM9GRdr5BCCHNqS3Wwud',
      },
      href: 'https://api.spotify.com/v1/albums/08eM9GRdr5BCCHNqS3Wwud',
      id: '08eM9GRdr5BCCHNqS3Wwud',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b27359e842b6a3566a141f27f815',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e0259e842b6a3566a141f27f815',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d0000485159e842b6a3566a141f27f815',
          width: 64,
        },
      ],
      name: 'Man On The Moon II: The Legend Of Mr. Rager',
      release_date: '2010-11-09',
      release_date_precision: 'day',
      total_tracks: 17,
      type: 'album',
      uri: 'spotify:album:08eM9GRdr5BCCHNqS3Wwud',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
        },
        href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
        id: '0fA0VVWsXO9YnASrzqfmYu',
        name: 'Kid Cudi',
        type: 'artist',
        uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x',
        },
        href: 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
        id: '5K4W6rqBFWDnAN6FQUkS6x',
        name: 'Kanye West',
        type: 'artist',
        uri: 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x',
      },
    ],
    available_markets: [
      'AD',
      'AE',
      'AG',
      'AL',
      'AM',
      'AO',
      'AR',
      'AT',
      'AU',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BN',
      'BO',
      'BR',
      'BS',
      'BT',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CD',
      'CG',
      'CH',
      'CI',
      'CL',
      'CM',
      'CO',
      'CR',
      'CV',
      'CW',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'ET',
      'FI',
      'FJ',
      'FM',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GH',
      'GM',
      'GN',
      'GQ',
      'GR',
      'GT',
      'GW',
      'GY',
      'HK',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IQ',
      'IS',
      'IT',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KR',
      'KW',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MG',
      'MH',
      'MK',
      'ML',
      'MN',
      'MO',
      'MR',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NE',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PG',
      'PH',
      'PK',
      'PL',
      'PT',
      'PW',
      'PY',
      'QA',
      'RO',
      'RS',
      'RW',
      'SA',
      'SB',
      'SC',
      'SE',
      'SG',
      'SI',
      'SK',
      'SL',
      'SM',
      'SN',
      'SR',
      'ST',
      'SV',
      'SZ',
      'TD',
      'TG',
      'TH',
      'TJ',
      'TL',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TW',
      'TZ',
      'UA',
      'UG',
      'US',
      'UY',
      'UZ',
      'VC',
      'VE',
      'VN',
      'VU',
      'WS',
      'XK',
      'ZA',
      'ZM',
      'ZW',
    ],
    disc_number: 1,
    duration_ms: 192253,
    explicit: true,
    external_ids: {
      isrc: 'USUM71020517',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/6XkuklKiHYVTlVvWlTgQYP',
    },
    href: 'https://api.spotify.com/v1/tracks/6XkuklKiHYVTlVvWlTgQYP',
    id: '6XkuklKiHYVTlVvWlTgQYP',
    is_local: false,
    name: 'Erase Me - Main',
    popularity: 71,
    preview_url:
      'https://p.scdn.co/mp3-preview/ed5b1d8a71c9991efae32e30d8317d299e6f0ff1?cid=af012268d5474f01b5237163a54e9b06',
    track_number: 8,
    type: 'track',
    uri: 'spotify:track:6XkuklKiHYVTlVvWlTgQYP',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
          },
          href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
          id: '0fA0VVWsXO9YnASrzqfmYu',
          name: 'Kid Cudi',
          type: 'artist',
          uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
        },
      ],
      available_markets: ['CA', 'MX', 'US'],
      external_urls: {
        spotify: 'https://open.spotify.com/album/2S8AWAM0nxyFy66YnUfIs3',
      },
      href: 'https://api.spotify.com/v1/albums/2S8AWAM0nxyFy66YnUfIs3',
      id: '2S8AWAM0nxyFy66YnUfIs3',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273a487deeecb334b6619489d74',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02a487deeecb334b6619489d74',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851a487deeecb334b6619489d74',
          width: 64,
        },
      ],
      name: 'Man On The Moon: The End Of Day (Deluxe)',
      release_date: '2009-01-01',
      release_date_precision: 'day',
      total_tracks: 18,
      type: 'album',
      uri: 'spotify:album:2S8AWAM0nxyFy66YnUfIs3',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
        },
        href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
        id: '0fA0VVWsXO9YnASrzqfmYu',
        name: 'Kid Cudi',
        type: 'artist',
        uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
      },
    ],
    available_markets: ['CA', 'MX', 'US'],
    disc_number: 1,
    duration_ms: 235626,
    explicit: true,
    external_ids: {
      isrc: 'USUM70981690',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/0rFpcfF0YfvFUYsl99Bw9d',
    },
    href: 'https://api.spotify.com/v1/tracks/0rFpcfF0YfvFUYsl99Bw9d',
    id: '0rFpcfF0YfvFUYsl99Bw9d',
    is_local: false,
    name: 'Soundtrack 2 My Life',
    popularity: 66,
    preview_url:
      'https://p.scdn.co/mp3-preview/a70bb40083aa600b118f02f4d71fda59251f895e?cid=af012268d5474f01b5237163a54e9b06',
    track_number: 2,
    type: 'track',
    uri: 'spotify:track:0rFpcfF0YfvFUYsl99Bw9d',
  },
  {
    album: {
      album_type: 'album',
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
          },
          href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
          id: '0fA0VVWsXO9YnASrzqfmYu',
          name: 'Kid Cudi',
          type: 'artist',
          uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
        },
      ],
      available_markets: ['CA', 'MX', 'US'],
      external_urls: {
        spotify: 'https://open.spotify.com/album/2S8AWAM0nxyFy66YnUfIs3',
      },
      href: 'https://api.spotify.com/v1/albums/2S8AWAM0nxyFy66YnUfIs3',
      id: '2S8AWAM0nxyFy66YnUfIs3',
      images: [
        {
          height: 640,
          url: 'https://i.scdn.co/image/ab67616d0000b273a487deeecb334b6619489d74',
          width: 640,
        },
        {
          height: 300,
          url: 'https://i.scdn.co/image/ab67616d00001e02a487deeecb334b6619489d74',
          width: 300,
        },
        {
          height: 64,
          url: 'https://i.scdn.co/image/ab67616d00004851a487deeecb334b6619489d74',
          width: 64,
        },
      ],
      name: 'Man On The Moon: The End Of Day (Deluxe)',
      release_date: '2009-01-01',
      release_date_precision: 'day',
      total_tracks: 18,
      type: 'album',
      uri: 'spotify:album:2S8AWAM0nxyFy66YnUfIs3',
    },
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/0fA0VVWsXO9YnASrzqfmYu',
        },
        href: 'https://api.spotify.com/v1/artists/0fA0VVWsXO9YnASrzqfmYu',
        id: '0fA0VVWsXO9YnASrzqfmYu',
        name: 'Kid Cudi',
        type: 'artist',
        uri: 'spotify:artist:0fA0VVWsXO9YnASrzqfmYu',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x',
        },
        href: 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
        id: '5K4W6rqBFWDnAN6FQUkS6x',
        name: 'Kanye West',
        type: 'artist',
        uri: 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/2GHclqNVjqGuiE5mA7BEoc',
        },
        href: 'https://api.spotify.com/v1/artists/2GHclqNVjqGuiE5mA7BEoc',
        id: '2GHclqNVjqGuiE5mA7BEoc',
        name: 'Common',
        type: 'artist',
        uri: 'spotify:artist:2GHclqNVjqGuiE5mA7BEoc',
      },
    ],
    available_markets: ['CA', 'MX', 'US'],
    disc_number: 1,
    duration_ms: 216413,
    explicit: true,
    external_ids: {
      isrc: 'USUM70982959',
    },
    external_urls: {
      spotify: 'https://open.spotify.com/track/7dZAPeA3Of5j5Vaef0DQ6M',
    },
    href: 'https://api.spotify.com/v1/tracks/7dZAPeA3Of5j5Vaef0DQ6M',
    id: '7dZAPeA3Of5j5Vaef0DQ6M',
    is_local: false,
    name: 'Make Her Say',
    popularity: 61,
    preview_url:
      'https://p.scdn.co/mp3-preview/3a35598633d5eaac4aaa4a20d4e618bb00f27689?cid=af012268d5474f01b5237163a54e9b06',
    track_number: 12,
    type: 'track',
    uri: 'spotify:track:7dZAPeA3Of5j5Vaef0DQ6M',
  },
]
